### ISSUE TITLE
Comparison with neopolars?

### ISSUE THREAD

**Issue by eitsupi** [etiennebacher/r-polars-dashboard#1]
If this is not difficult, is it worth comparing python polars and (R) neopolars?

I opened a PR to add `neopolars` to rpolars.r-universe.dev (rpolars/rpolars.r-universe.dev#5).

**Comment by etiennebacher** [comment]
I added two columns for this but it seems that latest commits (e.g. including str expressions) are not included in the output deployed on github pages (but they appear with my local version of neopolars). Is the version on r-polars.r-universe.org updated at every commit?

**Comment by eitsupi** [comment]
Thanks for the update!

> I added two columns for this but it seems that latest commits (e.g. including str expressions) are not included in the output deployed on github pages (but they appear with my local version of neopolars). Is the version on r-polars.r-universe.org updated at every commit?

Oh, sorry. It is deployed on every commit but not updated because I push it manually.
